// Indian Colleges and Universities Data
export const INDIAN_COLLEGES = [
  // IITs
  "Indian Institute of Technology (IIT) Bombay",
  "Indian Institute of Technology (IIT) Delhi",
  "Indian Institute of Technology (IIT) Madras",
  "Indian Institute of Technology (IIT) Kanpur",
  "Indian Institute of Technology (IIT) Kharagpur",
  "Indian Institute of Technology (IIT) Roorkee",
  "Indian Institute of Technology (IIT) Guwahati",
  "Indian Institute of Technology (IIT) Hyderabad",
  "Indian Institute of Technology (IIT) Indore",
  "Indian Institute of Technology (IIT) Mandi",
  "Indian Institute of Technology (IIT) Patna",
  "Indian Institute of Technology (IIT) Ropar",
  "Indian Institute of Technology (IIT) Bhubaneswar",
  "Indian Institute of Technology (IIT) Gandhinagar",
  "Indian Institute of Technology (IIT) Jodhpur",
  "Indian Institute of Technology (IIT) Varanasi (BHU)",
  "Indian Institute of Technology (IIT) Palakkad",
  "Indian Institute of Technology (IIT) Tirupati",
  "Indian Institute of Technology (IIT) Dhanbad",
  "Indian Institute of Technology (IIT) Bhilai",
  "Indian Institute of Technology (IIT) Goa",
  "Indian Institute of Technology (IIT) Jammu",
  "Indian Institute of Technology (IIT) Dharwad",

  // IIMs
  "Indian Institute of Management (IIM) Ahmedabad",
  "Indian Institute of Management (IIM) Bangalore",
  "Indian Institute of Management (IIM) Calcutta",
  "Indian Institute of Management (IIM) Lucknow",
  "Indian Institute of Management (IIM) Kozhikode",
  "Indian Institute of Management (IIM) Indore",
  "Indian Institute of Management (IIM) Shillong",
  "Indian Institute of Management (IIM) Rohtak",
  "Indian Institute of Management (IIM) Raipur",
  "Indian Institute of Management (IIM) Ranchi",
  "Indian Institute of Management (IIM) Tiruchirappalli",
  "Indian Institute of Management (IIM) Udaipur",
  "Indian Institute of Management (IIM) Kashipur",
  "Indian Institute of Management (IIM) Amritsar",
  "Indian Institute of Management (IIM) Bodh Gaya",
  "Indian Institute of Management (IIM) Nagpur",
  "Indian Institute of Management (IIM) Visakhapatnam",
  "Indian Institute of Management (IIM) Sirmaur",
  "Indian Institute of Management (IIM) Sambalpur",
  "Indian Institute of Management (IIM) Jammu",

  // NITs
  "National Institute of Technology (NIT) Trichy",
  "National Institute of Technology (NIT) Warangal",
  "National Institute of Technology (NIT) Surathkal",
  "National Institute of Technology (NIT) Calicut",
  "National Institute of Technology (NIT) Durgapur",
  "National Institute of Technology (NIT) Rourkela",
  "National Institute of Technology (NIT) Kurukshetra",
  "National Institute of Technology (NIT) Jamshedpur",
  "National Institute of Technology (NIT) Allahabad",
  "National Institute of Technology (NIT) Bhopal",
  "National Institute of Technology (NIT) Jalandhar",
  "National Institute of Technology (NIT) Patna",
  "National Institute of Technology (NIT) Raipur",
  "National Institute of Technology (NIT) Agartala",
  "National Institute of Technology (NIT) Arunachal Pradesh",
  "National Institute of Technology (NIT) Delhi",
  "National Institute of Technology (NIT) Goa",
  "National Institute of Technology (NIT) Hamirpur",
  "National Institute of Technology (NIT) Manipur",
  "National Institute of Technology (NIT) Meghalaya",
  "National Institute of Technology (NIT) Mizoram",
  "National Institute of Technology (NIT) Nagaland",
  "National Institute of Technology (NIT) Puducherry",
  "National Institute of Technology (NIT) Sikkim",
  "National Institute of Technology (NIT) Srinagar",
  "National Institute of Technology (NIT) Uttarakhand",

  // Central Universities
  "Jawaharlal Nehru University (JNU), Delhi",
  "University of Delhi (DU)",
  "Banaras Hindu University (BHU), Varanasi",
  "Aligarh Muslim University (AMU), Aligarh",
  "Jamia Millia Islamia, Delhi",
  "University of Hyderabad",
  "Pondicherry University",
  "Tezpur University, Assam",
  "North Eastern Hill University (NEHU), Shillong",
  "Manipur University",
  "Mizoram University",
  "Nagaland University",
  "Tripura University",
  "Assam University, Silchar",
  "Rajiv Gandhi University, Arunachal Pradesh",
  "Sikkim University",
  "University of Kashmir, Srinagar",
  "Hemvati Nandan Bahuguna Garhwal University",
  "H.N.B. Garhwal University, Uttarakhand",
  "Babasaheb Bhimrao Ambedkar University, Lucknow",
  "Jamia Hamdard, Delhi",
  "Indira Gandhi National Open University (IGNOU), Delhi",
  "English and Foreign Languages University (EFLU), Hyderabad",
  "Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya, Wardha",
  "Maulana Azad National Urdu University, Hyderabad",

  // State Universities
  "University of Mumbai",
  "University of Pune",
  "University of Calcutta",
  "University of Madras",
  "Osmania University, Hyderabad",
  "Andhra University, Visakhapatnam",
  "Kerala University, Thiruvananthapuram",
  "Cochin University of Science and Technology",
  "Anna University, Chennai",
  "Bharathiar University, Coimbatore",
  "Madurai Kamaraj University",
  "Periyar University, Salem",
  "Bharathidasan University, Tiruchirappalli",
  "Manonmaniam Sundaranar University, Tirunelveli",
  "Mother Teresa Women's University, Kodaikanal",
  "Tamil Nadu Agricultural University, Coimbatore",
  "Tamil Nadu Dr. M.G.R. Medical University, Chennai",
  "Tamil Nadu Veterinary and Animal Sciences University, Chennai",
  "Annamalai University, Chidambaram",
  "Alagappa University, Karaikudi",
  "Thiruvalluvar University, Vellore",
  "University of Agricultural Sciences, Bangalore",
  "Bangalore University",
  "Mysore University",
  "Mangalore University",
  "Kuvempu University, Shimoga",
  "Karnatak University, Dharwad",
  "Gulbarga University",
  "Visvesvaraya Technological University (VTU), Belgaum",
  "Rajiv Gandhi University of Health Sciences, Bangalore",
  "Karnataka State Open University, Mysore",

  // Private Universities
  "Birla Institute of Technology and Science (BITS), Pilani",
  "Vellore Institute of Technology (VIT), Vellore",
  "SRM Institute of Science and Technology, Chennai",
  "Manipal Academy of Higher Education",
  "Amity University",
  "Lovely Professional University (LPU), Punjab",
  "Shiv Nadar University, Greater Noida",
  "Ashoka University, Sonipat",
  "O.P. Jindal Global University, Sonipat",
  "Bennett University, Greater Noida",
  "Symbiosis International University, Pune",
  "MIT World Peace University, Pune",
  "Flame University, Pune",
  "Christ University, Bangalore",
  "PES University, Bangalore",
  "Jain University, Bangalore",
  "REVA University, Bangalore",
  "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar",
  "Siksha 'O' Anusandhan University, Bhubaneswar",
  "Centurion University, Bhubaneswar",
  "Thapar Institute of Engineering and Technology, Patiala",
  "Chitkara University, Punjab",
  "Chandigarh University",
  "Galgotias University, Greater Noida",
  "Jaypee Institute of Information Technology, Noida",
  "JSS Academy of Higher Education and Research, Mysore",
  "Nitte University, Mangalore",
  "Dayananda Sagar University, Bangalore",
  "Alliance University, Bangalore",
  "Azim Premji University, Bangalore",
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Delhi",
  "IIIT Allahabad",
  "IIIT Gwalior",
  "IIIT Jabalpur",
  "IIIT Kota",
  "IIIT Lucknow",
  "IIIT Nagpur",
  "IIIT Pune",
  "IIIT Sri City",
  "IIIT Vadodara",
  "IIIT Kalyani",
  "IIIT Kurnool",
  "IIIT Sonepat",
  "IIIT Una",
  "IIIT Bhopal",
  "IIIT Bhagalpur",
  "IIIT Agartala",
  "IIIT Dharwad",
  "IIIT Kottayam",
  "IIIT Ranchi",
  "IIIT Tiruchirappalli",
  "IIIT Guwahati",
  "IIIT Manipur",
  "IIIT Surat",
  "IIIT Raichur",
].sort()

// Academic Departments
export const ACADEMIC_DEPARTMENTS = [
  // Engineering & Technology
  "Computer Science and Engineering",
  "Information Technology",
  "Electronics and Communication Engineering",
  "Electrical and Electronics Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Automobile Engineering",
  "Biomedical Engineering",
  "Biotechnology Engineering",
  "Environmental Engineering",
  "Industrial Engineering",
  "Materials Science and Engineering",
  "Mining Engineering",
  "Petroleum Engineering",
  "Production Engineering",
  "Textile Engineering",
  "Agricultural Engineering",
  "Food Technology",
  "Instrumentation Engineering",
  "Metallurgical Engineering",
  "Naval Architecture and Ocean Engineering",
  "Robotics and Automation",
  "Software Engineering",
  "Artificial Intelligence and Machine Learning",
  "Data Science and Engineering",
  "Cyber Security",
  "Internet of Things (IoT)",
  "Blockchain Technology",

  // Science
  "Physics",
  "Chemistry",
  "Mathematics",
  "Statistics",
  "Biology",
  "Botany",
  "Zoology",
  "Microbiology",
  "Biochemistry",
  "Biophysics",
  "Biotechnology",
  "Environmental Science",
  "Geology",
  "Geography",
  "Astronomy",
  "Atmospheric Science",
  "Marine Science",
  "Forensic Science",
  "Applied Sciences",
  "Life Sciences",
  "Physical Sciences",
  "Earth Sciences",
  "Materials Science",
  "Nanotechnology",
  "Bioinformatics",
  "Computational Biology",

  // Medicine & Health Sciences
  "Medicine (MBBS)",
  "Dental Surgery (BDS)",
  "Pharmacy",
  "Nursing",
  "Physiotherapy",
  "Occupational Therapy",
  "Medical Laboratory Technology",
  "Radiology and Imaging Technology",
  "Optometry",
  "Audiology and Speech Language Pathology",
  "Public Health",
  "Community Medicine",
  "Ayurveda",
  "Homeopathy",
  "Unani Medicine",
  "Siddha Medicine",
  "Naturopathy and Yogic Sciences",
  "Veterinary Science",
  "Animal Husbandry",
  "Dairy Technology",

  // Management & Business
  "Business Administration",
  "Management Studies",
  "Finance",
  "Marketing",
  "Human Resource Management",
  "Operations Management",
  "International Business",
  "Entrepreneurship",
  "Supply Chain Management",
  "Business Analytics",
  "Digital Marketing",
  "E-commerce",
  "Retail Management",
  "Banking and Insurance",
  "Financial Markets",
  "Investment Management",
  "Corporate Finance",
  "Management Information Systems",
  "Project Management",
  "Quality Management",

  // Arts & Humanities
  "English Literature",
  "Hindi Literature",
  "Sanskrit",
  "Tamil Literature",
  "Telugu Literature",
  "Bengali Literature",
  "Marathi Literature",
  "Gujarati Literature",
  "Punjabi Literature",
  "Urdu Literature",
  "History",
  "Political Science",
  "Sociology",
  "Psychology",
  "Philosophy",
  "Economics",
  "Anthropology",
  "Archaeology",
  "Linguistics",
  "Library and Information Science",
  "Mass Communication and Journalism",
  "Film Studies",
  "Theatre Arts",
  "Fine Arts",
  "Applied Arts",
  "Music",
  "Dance",
  "Painting",
  "Sculpture",
  "Photography",
  "Creative Writing",
  "Translation Studies",
  "Cultural Studies",
  "Gender Studies",
  "International Relations",
  "Public Administration",
  "Social Work",
  "Criminology",
  "Human Rights",

  // Law
  "Law (LLB)",
  "Constitutional Law",
  "Criminal Law",
  "Corporate Law",
  "International Law",
  "Intellectual Property Law",
  "Environmental Law",
  "Cyber Law",
  "Tax Law",
  "Labour Law",
  "Family Law",
  "Commercial Law",
  "Banking Law",
  "Human Rights Law",

  // Education
  "Education",
  "Elementary Education",
  "Secondary Education",
  "Special Education",
  "Educational Psychology",
  "Educational Technology",
  "Curriculum and Instruction",
  "Educational Administration",
  "Adult Education",
  "Distance Education",
  "Physical Education",
  "Sports Science",
  "Yoga Education",

  // Commerce & Economics
  "Commerce",
  "Accounting",
  "Business Economics",
  "Banking and Finance",
  "Taxation",
  "Auditing",
  "Cost Accounting",
  "Management Accounting",
  "Financial Accounting",
  "Corporate Accounting",
  "International Finance",
  "Investment Analysis",
  "Risk Management",
  "Insurance",
  "Capital Markets",
  "Econometrics",
  "Development Economics",
  "Agricultural Economics",
  "Industrial Economics",
  "Environmental Economics",

  // Agriculture & Allied Sciences
  "Agriculture",
  "Horticulture",
  "Forestry",
  "Agricultural Economics",
  "Agricultural Engineering",
  "Plant Pathology",
  "Entomology",
  "Soil Science",
  "Agronomy",
  "Plant Breeding and Genetics",
  "Agricultural Extension",
  "Agricultural Statistics",
  "Food Science and Technology",
  "Dairy Science",
  "Poultry Science",
  "Fisheries Science",
  "Sericulture",
  "Agricultural Marketing",
  "Organic Farming",
  "Sustainable Agriculture",

  // Architecture & Design
  "Architecture",
  "Interior Design",
  "Urban Planning",
  "Landscape Architecture",
  "Industrial Design",
  "Fashion Design",
  "Graphic Design",
  "Product Design",
  "Textile Design",
  "Jewelry Design",
  "Animation and Multimedia",
  "Game Design",
  "User Experience (UX) Design",
  "User Interface (UI) Design",
  "Web Design",
  "Visual Communication",

  // Hotel Management & Tourism
  "Hotel Management",
  "Tourism Management",
  "Hospitality Management",
  "Culinary Arts",
  "Food and Beverage Management",
  "Event Management",
  "Travel and Tourism",
  "Aviation Management",
  "Cruise Management",
  "Resort Management",

  // Other Professional Courses
  "Chartered Accountancy (CA)",
  "Company Secretary (CS)",
  "Cost and Management Accountancy (CMA)",
  "Actuarial Science",
  "Digital Marketing",
  "Data Analytics",
  "Cloud Computing",
  "DevOps",
  "Full Stack Development",
  "Mobile App Development",
  "Game Development",
  "Ethical Hacking",
  "Network Security",
  "Database Administration",
  "System Administration",
  "Quality Assurance",
  "Technical Writing",
  "Project Management",
  "Business Analysis",
  "Product Management",
].sort()

// Academic Courses for Students
export const ACADEMIC_COURSES = [
  // Undergraduate Engineering
  "B.Tech Computer Science and Engineering",
  "B.Tech Information Technology",
  "B.Tech Electronics and Communication Engineering",
  "B.Tech Electrical and Electronics Engineering",
  "B.Tech Mechanical Engineering",
  "B.Tech Civil Engineering",
  "B.Tech Chemical Engineering",
  "B.Tech Aerospace Engineering",
  "B.Tech Automobile Engineering",
  "B.Tech Biomedical Engineering",
  "B.Tech Biotechnology Engineering",
  "B.Tech Environmental Engineering",
  "B.Tech Industrial Engineering",
  "B.Tech Materials Science and Engineering",
  "B.Tech Mining Engineering",
  "B.Tech Petroleum Engineering",
  "B.Tech Production Engineering",
  "B.Tech Textile Engineering",
  "B.Tech Agricultural Engineering",
  "B.Tech Food Technology",
  "B.Tech Instrumentation Engineering",
  "B.Tech Metallurgical Engineering",
  "B.Tech Robotics and Automation",
  "B.Tech Software Engineering",
  "B.Tech Artificial Intelligence and Machine Learning",
  "B.Tech Data Science and Engineering",
  "B.Tech Cyber Security",

  // Postgraduate Engineering
  "M.Tech Computer Science and Engineering",
  "M.Tech Information Technology",
  "M.Tech Electronics and Communication Engineering",
  "M.Tech Electrical and Electronics Engineering",
  "M.Tech Mechanical Engineering",
  "M.Tech Civil Engineering",
  "M.Tech Chemical Engineering",
  "M.Tech Aerospace Engineering",
  "M.Tech Automobile Engineering",
  "M.Tech Biomedical Engineering",
  "M.Tech Biotechnology Engineering",
  "M.Tech Environmental Engineering",
  "M.Tech Industrial Engineering",
  "M.Tech Materials Science and Engineering",
  "M.Tech Mining Engineering",
  "M.Tech Petroleum Engineering",
  "M.Tech Production Engineering",
  "M.Tech Textile Engineering",
  "M.Tech Agricultural Engineering",
  "M.Tech Food Technology",
  "M.Tech Instrumentation Engineering",
  "M.Tech Metallurgical Engineering",
  "M.Tech Robotics and Automation",
  "M.Tech Software Engineering",
  "M.Tech Artificial Intelligence and Machine Learning",
  "M.Tech Data Science and Engineering",
  "M.Tech Cyber Security",

  // Science Undergraduate
  "B.Sc Physics",
  "B.Sc Chemistry",
  "B.Sc Mathematics",
  "B.Sc Statistics",
  "B.Sc Biology",
  "B.Sc Botany",
  "B.Sc Zoology",
  "B.Sc Microbiology",
  "B.Sc Biochemistry",
  "B.Sc Biophysics",
  "B.Sc Biotechnology",
  "B.Sc Environmental Science",
  "B.Sc Geology",
  "B.Sc Geography",
  "B.Sc Computer Science",
  "B.Sc Information Technology",
  "B.Sc Electronics",
  "B.Sc Applied Sciences",
  "B.Sc Life Sciences",
  "B.Sc Physical Sciences",
  "B.Sc Earth Sciences",
  "B.Sc Materials Science",
  "B.Sc Nanotechnology",
  "B.Sc Bioinformatics",
  "B.Sc Data Science",
  "B.Sc Artificial Intelligence",
  "B.Sc Cyber Security",
  "B.Sc Animation and Multimedia",
  "B.Sc Game Development",
  "B.Sc Web Development",

  // Science Postgraduate
  "M.Sc Physics",
  "M.Sc Chemistry",
  "M.Sc Mathematics",
  "M.Sc Statistics",
  "M.Sc Biology",
  "M.Sc Botany",
  "M.Sc Zoology",
  "M.Sc Microbiology",
  "M.Sc Biochemistry",
  "M.Sc Biophysics",
  "M.Sc Biotechnology",
  "M.Sc Environmental Science",
  "M.Sc Geology",
  "M.Sc Geography",
  "M.Sc Computer Science",
  "M.Sc Information Technology",
  "M.Sc Electronics",
  "M.Sc Applied Sciences",
  "M.Sc Life Sciences",
  "M.Sc Physical Sciences",
  "M.Sc Earth Sciences",
  "M.Sc Materials Science",
  "M.Sc Nanotechnology",
  "M.Sc Bioinformatics",
  "M.Sc Data Science",
  "M.Sc Artificial Intelligence",
  "M.Sc Cyber Security",

  // Medicine & Health Sciences
  "MBBS (Bachelor of Medicine and Bachelor of Surgery)",
  "BDS (Bachelor of Dental Surgery)",
  "B.Pharm (Bachelor of Pharmacy)",
  "D.Pharm (Diploma in Pharmacy)",
  "B.Sc Nursing",
  "GNM (General Nursing and Midwifery)",
  "BPT (Bachelor of Physiotherapy)",
  "BOT (Bachelor of Occupational Therapy)",
  "BMLT (Bachelor of Medical Laboratory Technology)",
  "BRIT (Bachelor of Radiology and Imaging Technology)",
  "B.Optom (Bachelor of Optometry)",
  "BASLP (Bachelor of Audiology and Speech Language Pathology)",
  "MPH (Master of Public Health)",
  "MD (Doctor of Medicine)",
  "MS (Master of Surgery)",
  "MDS (Master of Dental Surgery)",
  "M.Pharm (Master of Pharmacy)",
  "M.Sc Nursing",
  "MPT (Master of Physiotherapy)",
  "MOT (Master of Occupational Therapy)",
  "BAMS (Bachelor of Ayurvedic Medicine and Surgery)",
  "BHMS (Bachelor of Homeopathic Medicine and Surgery)",
  "BUMS (Bachelor of Unani Medicine and Surgery)",
  "BSMS (Bachelor of Siddha Medicine and Surgery)",
  "BNYS (Bachelor of Naturopathy and Yogic Sciences)",
  "BVSc (Bachelor of Veterinary Science)",
  "MVSc (Master of Veterinary Science)",

  // Management & Business
  "BBA (Bachelor of Business Administration)",
  "MBA (Master of Business Administration)",
  "PGDM (Post Graduate Diploma in Management)",
  "B.Com (Bachelor of Commerce)",
  "M.Com (Master of Commerce)",
  "BMS (Bachelor of Management Studies)",
  "BBM (Bachelor of Business Management)",
  "BFM (Bachelor of Financial Management)",
  "BHM (Bachelor of Hotel Management)",
  "BTTM (Bachelor of Travel and Tourism Management)",
  "Executive MBA",
  "MBA Finance",
  "MBA Marketing",
  "MBA Human Resource Management",
  "MBA Operations Management",
  "MBA International Business",
  "MBA Entrepreneurship",
  "MBA Supply Chain Management",
  "MBA Business Analytics",
  "MBA Digital Marketing",
  "MBA Healthcare Management",
  "MBA Rural Management",
  "MBA Agribusiness Management",
  "MBA Sports Management",
  "MBA Media Management",

  // Arts & Humanities
  "BA (Bachelor of Arts)",
  "MA (Master of Arts)",
  "BA English Literature",
  "MA English Literature",
  "BA Hindi Literature",
  "MA Hindi Literature",
  "BA History",
  "MA History",
  "BA Political Science",
  "MA Political Science",
  "BA Sociology",
  "MA Sociology",
  "BA Psychology",
  "MA Psychology",
  "BA Philosophy",
  "MA Philosophy",
  "BA Economics",
  "MA Economics",
  "BA Geography",
  "MA Geography",
  "BA Anthropology",
  "MA Anthropology",
  "BA Archaeology",
  "MA Archaeology",
  "BA Linguistics",
  "MA Linguistics",
  "BLIS (Bachelor of Library and Information Science)",
  "MLIS (Master of Library and Information Science)",
  "BJMC (Bachelor of Journalism and Mass Communication)",
  "MJMC (Master of Journalism and Mass Communication)",
  "BFA (Bachelor of Fine Arts)",
  "MFA (Master of Fine Arts)",
  "BPA (Bachelor of Performing Arts)",
  "MPA (Master of Performing Arts)",
  "BA Music",
  "MA Music",
  "BA Social Work",
  "MSW (Master of Social Work)",

  // Law
  "LLB (Bachelor of Laws)",
  "BA LLB (Integrated)",
  "BBA LLB (Integrated)",
  "B.Com LLB (Integrated)",
  "BSc LLB (Integrated)",
  "LLM (Master of Laws)",
  "LLM Constitutional Law",
  "LLM Criminal Law",
  "LLM Corporate Law",
  "LLM International Law",
  "LLM Intellectual Property Law",
  "LLM Environmental Law",
  "LLM Cyber Law",
  "LLM Tax Law",
  "LLM Labour Law",
  "LLM Human Rights Law",

  // Education
  "B.Ed (Bachelor of Education)",
  "M.Ed (Master of Education)",
  "D.El.Ed (Diploma in Elementary Education)",
  "B.P.Ed (Bachelor of Physical Education)",
  "M.P.Ed (Master of Physical Education)",
  "BPE (Bachelor of Physical Education)",
  "MPE (Master of Physical Education)",
  "B.Sc Physical Education",
  "M.Sc Physical Education",
  "Diploma in Education",
  "Certificate in Education",

  // Agriculture & Allied Sciences
  "B.Sc Agriculture",
  "M.Sc Agriculture",
  "B.Sc Horticulture",
  "M.Sc Horticulture",
  "B.Sc Forestry",
  "M.Sc Forestry",
  "B.Sc Agricultural Economics",
  "M.Sc Agricultural Economics",
  "B.Tech Agricultural Engineering",
  "M.Tech Agricultural Engineering",
  "B.Sc Plant Pathology",
  "M.Sc Plant Pathology",
  "B.Sc Entomology",
  "M.Sc Entomology",
  "B.Sc Soil Science",
  "M.Sc Soil Science",
  "B.Sc Agronomy",
  "M.Sc Agronomy",
  "B.Sc Plant Breeding and Genetics",
  "M.Sc Plant Breeding and Genetics",
  "B.Sc Food Science and Technology",
  "M.Sc Food Science and Technology",
  "B.Sc Dairy Science",
  "M.Sc Dairy Science",
  "B.Sc Fisheries Science",
  "M.Sc Fisheries Science",

  // Architecture & Design
  "B.Arch (Bachelor of Architecture)",
  "M.Arch (Master of Architecture)",
  "B.Des (Bachelor of Design)",
  "M.Des (Master of Design)",
  "B.Planning (Bachelor of Planning)",
  "M.Planning (Master of Planning)",
  "Diploma in Interior Design",
  "Diploma in Fashion Design",
  "Diploma in Graphic Design",
  "Diploma in Product Design",
  "Diploma in Textile Design",
  "Diploma in Jewelry Design",
  "Diploma in Animation and Multimedia",
  "Diploma in Game Design",
  "Certificate in Web Design",
  "Certificate in UI/UX Design",

  // Hotel Management & Tourism
  "BHM (Bachelor of Hotel Management)",
  "BHMCT (Bachelor of Hotel Management and Catering Technology)",
  "Diploma in Hotel Management",
  "Certificate in Hotel Management",
  "BTTM (Bachelor of Travel and Tourism Management)",
  "Diploma in Travel and Tourism",
  "Certificate in Travel and Tourism",
  "Diploma in Culinary Arts",
  "Certificate in Food Production",
  "Certificate in Food and Beverage Service",
  "Certificate in Front Office Operations",
  "Certificate in Housekeeping Operations",

  // Professional Courses
  "CA (Chartered Accountancy)",
  "CS (Company Secretary)",
  "CMA (Cost and Management Accountancy)",
  "CFA (Chartered Financial Analyst)",
  "FRM (Financial Risk Manager)",
  "ACCA (Association of Chartered Certified Accountants)",
  "CPA (Certified Public Accountant)",
  "Diploma in Digital Marketing",
  "Certificate in Data Analytics",
  "Certificate in Cloud Computing",
  "Certificate in DevOps",
  "Certificate in Full Stack Development",
  "Certificate in Mobile App Development",
  "Certificate in Game Development",
  "Certificate in Ethical Hacking",
  "Certificate in Network Security",
  "Certificate in Database Administration",
  "Certificate in System Administration",
  "Certificate in Quality Assurance",
  "Certificate in Technical Writing",
  "Certificate in Project Management",
  "Certificate in Business Analysis",
  "Certificate in Product Management",

  // Doctoral Programs
  "Ph.D Computer Science",
  "Ph.D Information Technology",
  "Ph.D Electronics and Communication",
  "Ph.D Electrical Engineering",
  "Ph.D Mechanical Engineering",
  "Ph.D Civil Engineering",
  "Ph.D Chemical Engineering",
  "Ph.D Physics",
  "Ph.D Chemistry",
  "Ph.D Mathematics",
  "Ph.D Biology",
  "Ph.D Biotechnology",
  "Ph.D Management",
  "Ph.D Economics",
  "Ph.D English Literature",
  "Ph.D History",
  "Ph.D Political Science",
  "Ph.D Sociology",
  "Ph.D Psychology",
  "Ph.D Philosophy",
  "Ph.D Education",
  "Ph.D Law",
  "Ph.D Medicine",
  "Ph.D Agriculture",
  "Ph.D Architecture",
].sort()

// Gender options
export const GENDER_OPTIONS = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
]

// Academic years
export const ACADEMIC_YEARS = [
  "2024-2025",
  "2023-2024",
  "2022-2023",
  "2021-2022",
  "2020-2021",
  "2019-2020",
  "2018-2019",
  "2017-2018",
]

// Semester options
export const SEMESTER_OPTIONS = Array.from({ length: 12 }, (_, i) => ({
  value: (i + 1).toString(),
  label: `Semester ${i + 1}`,
}))

// Experience years for teachers
export const EXPERIENCE_YEARS = Array.from({ length: 51 }, (_, i) => ({
  value: i.toString(),
  label: i === 0 ? "Fresher" : `${i} ${i === 1 ? "Year" : "Years"}`,
}))
